# file: roles/supervisor/handlers/main.yml

- name: restart supervisor
  service: name=supervisord state=restarted
  sudo: yes

- name: start supervisor
  service: name=supervisord state=started
  sudo: yes

- name: start supervisor
  service: name=supervisord state=stopped
  sudo: yes

- name: enable supervisor
  service: name=supervisord enabled=yes
  sudo: yes
