# file: roles/storm_common/tasks/configure.yml

- name: Storm | Create log directory
  file:
    path={{ storm_log_dir }}
    state=directory
    owner={{ storm_user }}
    group=root
    mode=0644

- name: Storm | Update the storm configuration
  template:
    src=storm_conf.yaml.j2
    dest={{ storm_home }}/conf/storm.yaml
    owner={{ storm_user }}
    group={{ storm_group }}
    mode=0644
