# file: roles/storm_common/tasks/jzmq.yml

- name: Storm | (jzmq) Gather additional facts
  set_fact:
    jzmq_home: /tmp/jzmq
  tags:
    - jzmq

- name: Storm | (jzmq) Download jzmq source from the git repo
  git:
    repo=https://github.com/instilled/jzmq.git
    dest={{ jzmq_home }}
  tags:
    - jzmq

- name: Storm | (jzmq) Fix jzmq install for ubuntu - pt. 1
  shell:
    touch {{ jzmq_home }}/src/classdist_noinst.stamp
    chdir={{ jzmq_home }}/src
    creates={{ jzmq_home }}/src/classdist_noinst.stamp
  tags:
    - jzmq

- name: Storm | (jzmq) Invoke autotools
  shell:
    ./autogen.sh
    chdir={{ jzmq_home }}
  tags:
    - jzmq

- name: Storm | (jzmq) Configure jzmq source
  shell:
    export JAVA_HOME={{ java_home }} && ./configure
    chdir={{ jzmq_home }}
  tags:
    - jzmq

- name: Storm | (jzmq) Patch jzmq install for ubuntu - pt. 2
  shell:
    cd {{ jzmq_home }}/src && javac -d . org/zeromq/*.java
  tags:
    - jzmq

- name: Storm | (jzmq) Build the jzmq source
  shell:
    cd {{ jzmq_home }}/src && JAVA_HOME={{ java_home }} make -j $machine_cpu_count
  tags:
    - jzmq

- name: Storm | (jzmq) Install jzmq
  shell:
    make install
    chdir={{ jzmq_home }}
  tags:
    - jzmq