# file: roles/storm_common/tasks/main.yml

- name: Storm | Make sure storm is not running under supervisord
  supervisorctl: name={{ item }} state=stopped
  with_items:
    - storm-drpc
    - storm-nimbus
    - storm-ui
    - storm-supervisor
  tags:
    - storm-common

- include: dependencies.yml
  tags:
    - storm-common

- include: jzmq.yml
  tags:
    - storm-common

- include: user.yml
  tags:
    - storm-common

- include: install.yml
  tags:
    - storm-common

- include: configure.yml
  tags:
    - storm-common
