# file: roles/supervisor/tasks/main.yml

- name: Supervisor | Make sure supervisor is installed
  pip: name=supervisor version={{ supervisor_version }}
  tags:
    - supervisor

- name: Supervisor | Make sure the supervisor conf dir exists
  file:
    path={{ supervisor_dir }}
    state=directory
    mode=0755
    owner=root
    group=root
  tags:
    - supervisor

- name: Supervisor | Update the global supervisor configuration
  template:
    src=etc_supervisord.conf.j2
    dest={{ supervisord_conf }}
    owner=root
    group=root
    mode=0644
  tags:
    - supervisor

- name: Supervisor | Make sure the supervisor log dir exists
  file:
    path={{ supervisor_log_dir }}
    state=directory
    owner=root
    group=root
    mode=0755
    recurse=yes
  tags:
    - supervisor

- name: Supervisor | Install the supervisor upstart conf
  template:
    src=etc_init_supervisord.conf.j2
    dest=/etc/init/supervisord.conf
    owner=root
    group=root
    mode=0755
  notify:
    - enable supervisor
    - restart supervisor
  tags:
    - supervisor
