# file: roles/jdk/tasks/main.yml

- name: JDK | Oracle JDK | Make sure openjdk is uninstalled
  apt: pkg=openjdk state=absent purge=true
  tags:
    - java

- name: JDK | Oracle JDK | Download Oracle JDK
  command:
    wget --no-cookies --header 'Cookie:oraclelicense=accept-securebackup-cookie' '{{ jdk_download_url }}' 
    chdir=/tmp
    creates={{ java_install_dir }}/{{ jdk_version }}
  tags:
    - java

- name: JDK | Oracle JDK | Unpack the compressed JDK binaries
  command:
    tar -xvzf /tmp/{{ jdk_download_filename }}
    chdir={{ java_install_dir }}
    creates={{ java_install_dir }}/{{ jdk_version }}
  tags:
    - java

- name: JDK | Oracle JDK | Create symlink to JDK install
  file:
    path={{ java_home }}
    src={{ java_install_dir }}/{{ jdk_version }}
    state=link
    force=yes
  tags:
    - java

- name: JDK | Oracle JDK | Add JDK binaries to the system path (/etc/profile.d/java.sh)
  template:
    src=etc_profile.d_java.sh
    dest=/etc/profile.d/java.sh
    mode=644
    group=root owner=root
  tags:
    - java

# Not really sure we need to update alternatives for all of the java tools
- name: JDK | Oracle JDK | Inform the system where Oracle JDK is located
  command: update-alternatives --install "/usr/bin/{{ item }}" {{ item }} "{{ java_home }}/bin/{{ item }}" 1
  with_items:
    - java
    - javac
    - javaws
    - javah
    - jar
  tags:
    - java

- name: JDK | Oracle JDK | Inform the system that Oracle JDK must be the default
  command: update-alternatives --set "{{ item }}" "{{ java_home }}/bin/{{ item }}"
  with_items:
    - java
    - javac
    - javaws
    - javah
    - jar
  tags:
    - java
